In [1]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(data)
print()

print("4.", data.shape)
print("5.", data.ndim)
print("6.", data.size)
print("7.", data.dtype)
print()

print("8.", np.sum(data))
print("9.", np.mean(data))
print("10.", np.std(data))
print("11.", np.max(data))
print("12.", np.min(data))
print()

print("13.")
print(data.T)
print()

print("14.")
reshaped = data.reshape(1, 9)
print(reshaped)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

4. (3, 3)
5. 2
6. 9
7. int64

8. 45
9. 5.0
10. 2.581988897471611
11. 9
12. 1

13.
[[1 4 7]
 [2 5 8]
 [3 6 9]]

14.
[[1 2 3 4 5 6 7 8 9]]



In [2]:
import pandas as pd
import numpy as np

print("1. Create a simple DataFrame:")
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 28, 32],
    'City': ['New York', 'London', 'Tokyo', 'Paris', 'Sydney'],
    'Salary': [50000, 60000, 70000, 55000, 65000],
    'Department': ['IT', 'Sales', 'IT', 'Marketing', 'Sales']
}
df = pd.DataFrame(data)
print(df)
print()

print("2. DataFrame info:")
print(df.info())
print()

print("3. Basic statistics:")
print(df.describe())
print()

print("4. First 2 rows:")
print(df.head(2))
print()

print("5. Last 2 rows:")
print(df.tail(2))
print()

print("6. Select Name column:")
print(df['Name'])
print()

print("7. Select multiple columns:")
print(df[['Name', 'Age', 'Salary']])
print()

print("8. Select row 1:")
print(df.iloc[1])
print()

print("9. Filter Age > 30:")
print(df[df['Age'] > 30])
print()

print("10. Filter IT department:")
print(df[df['Department'] == 'IT'])
print()

print("11. Sort by Salary (descending):")
print(df.sort_values('Salary', ascending=False))
print()

print("12. Average salary by department:")
print(df.groupby('Department')['Salary'].mean())
print()

print("13. Add Annual Salary column:")
df['Annual_Salary'] = df['Salary'] * 12
print(df)
print()

print("14. Create DataFrame with missing values:")
df_missing = df.copy()
df_missing.loc[1, 'Salary'] = np.nan
df_missing.loc[3, 'Age'] = np.nan
print(df_missing)
print()

print("15. Check for missing values:")
print(df_missing.isnull().sum())
print()

print("18. Rename columns:")
df_renamed = df.rename(columns={'Annual_Salary': 'Yearly_Income'})
print(df_renamed.columns.tolist())
print()

print("19. Drop column:")
df_dropped = df.drop(columns=['Annual_Salary'])
print(df_dropped.columns.tolist())

1. Create a simple DataFrame:
      Name  Age      City  Salary Department
0    Alice   25  New York   50000         IT
1      Bob   30    London   60000      Sales
2  Charlie   35     Tokyo   70000         IT
3    David   28     Paris   55000  Marketing
4      Eva   32    Sydney   65000      Sales

2. DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        5 non-null      object
 1   Age         5 non-null      int64 
 2   City        5 non-null      object
 3   Salary      5 non-null      int64 
 4   Department  5 non-null      object
dtypes: int64(2), object(3)
memory usage: 328.0+ bytes
None

3. Basic statistics:
             Age       Salary
count   5.000000      5.00000
mean   30.000000  60000.00000
std     3.807887   7905.69415
min    25.000000  50000.00000
25%    28.000000  55000.00000
50%    30.000000  60000.00000
75%    3